version: 2

workflows:
  version: 2
  workflow:
    jobs:
      - test-3.7
      - test-3.8
      - test-3.9

defaults: &defaults
  working_directory: ~/code
  steps:
  - checkout
  - run:
      name: Install dependencies
      command: pip install --user -r requirements.txt nose
  - run:
      name: Lint
      command: flake8 flask_mongorest
  - run:
      name: Test
      command: nosetests

jobs:
  test-3.7:
    <<: *defaults
    docker:
    - image: circleci/python:3.7
    - image: mongo:3.2.19
  test-3.8:
    <<: *defaults
    docker:
      - image: circleci/python:3.8
      - image: mongo:3.2.19
  test-3.9:
    <<: *defaults
    docker:
      - image: circleci/python:3.9
      - image: mongo:3.2.19
