# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: flask_mongorest/cursors.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='flask_mongorest/cursors.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x1d\x66lask_mongorest/cursors.proto\"=\n\x10SequentialCursor\x12\x0c\n\x04time\x18\x01 \x01(\r\x12\x0c\n\x04skip\x18\x02 \x01(\x04\x12\r\n\x05limit\x18\x03 \x01(\x04\x62\x06proto3')
)




_SEQUENTIALCURSOR = _descriptor.Descriptor(
  name='SequentialCursor',
  full_name='SequentialCursor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='time', full_name='SequentialCursor.time', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='skip', full_name='SequentialCursor.skip', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='limit', full_name='SequentialCursor.limit', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=94,
)

DESCRIPTOR.message_types_by_name['SequentialCursor'] = _SEQUENTIALCURSOR
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SequentialCursor = _reflection.GeneratedProtocolMessageType('SequentialCursor', (_message.Message,), dict(
  DESCRIPTOR = _SEQUENTIALCURSOR,
  __module__ = 'flask_mongorest.cursors_pb2'
  # @@protoc_insertion_point(class_scope:SequentialCursor)
  ))
_sym_db.RegisterMessage(SequentialCursor)


# @@protoc_insertion_point(module_scope)
